MagicDuck/grug-far.nvim

- lua/grug-far/farBuffer.lua
When you have a global keymap like `<enter><enter>`, there will be a delay when pressing `<enter>`. `nowait` removes that delay.
> fix: remove delay from keymaps

- lua/grug-far/health.lua
Great plugin so far, excited to see where it goes!
Running on 0.10/HEAD I get the following deprecation warnings when performing the health check:
Looks like they are marked as deprecated in 0.10 and will be removed in 0.11. See https://neovim.io/doc/user/deprecated.html  and neovim/neovim#22927
This updates the function calls to use the new versions.
> Update health functions to use non-deprecated versions.

- README.md
- lua/grug-far/actions/replace.lua
- lua/grug-far/actions/syncLocations.lua
- lua/grug-far/farBuffer.lua
- lua/grug-far/opts.lua
- lua/grug-far/render/help.lua
- lua/grug-far/render/resultsList.lua
> Add ability to sync locations after making changes in the results area

- README.md
- doc/grug-far.txt
- lua/grug-far.lua
- lua/grug-far/opts.lua
`GrugFar` command and `require('grug-far').grug_far(opts)` will now pre-fill search with visual selection in visual mode.
`with_visual_selection(opts)` is only necessary if you want to use the visual selection from lua command mode. ex:
```
:lua require('grug-far').with_visual_selection(opts)
```
fixes https://github.com/MagicDuck/grug-far.nvim/issues/119
> Consolidate visual mode api

- README.md
Grug requires the use of the recently added `--hyperlink-format` flag (introduced in `rg` release [14.0](https://github.com/BurntSushi/ripgrep/releases/tag/14.0.0)).
Many Debian instances (e.g., WSL running Ubuntu-22.04) have a stable packaged ripgrep instance of version 13.0.0.
To clarify dependencies to users I suggest we add the `rg` dependency requirement to the readme. This way we avoid breaking any builds, but still inform users about constraints.
> Update README requirements to Include ripgrep Version

- lua/grug-far/farBuffer.lua
- lua/grug-far/opts.lua
- lua/grug-far/utils.lua
When opening grug, it essentially creates a "temporary window" which I don't want to show up in my tabline/bufferline plugins. This makes it so that the buffer is unlisted similar to other similar plugins such as `nvim-spectre`.
Thanks so much for an awesome plugin!
> feat: add the ability to create transient search buffers

- lua/grug-far/render/resultsList.lua
fixes https://github.com/MagicDuck/grug-far.nvim/issues/234
> fixing crash in nighly due to extmarks being cleared after buffer lines are removed

- README.md
- lua/grug-far.lua
- lua/grug-far/engine.lua
- lua/grug-far/fileIconsProvider.lua
- lua/grug-far/opts.lua
- lua/grug-far/render/resultsList.lua
fixes https://github.com/MagicDuck/grug-far.nvim/issues/182
> adding file icons

- README.md
I noticed there is a really cool new recipe for neo-tree integration with grug-far! This is super awesome, so I wanted to recommend an improvement that utilizes the built in command/mapping features in Neo-tree. This also means that the new binding shows up in the neo-tree help when you press `?`.
I also added a similar recipe for adding the same type of command in oil.nvim.
Let me know what you think!
> File explorer recipe improvements

- doc/grug-far.txt
- lua/grug-far.lua
- lua/grug-far/engine.lua
- lua/grug-far/engine/astgrep.lua
- lua/grug-far/engine/ripgrep.lua
- lua/grug-far/utils.lua
While playing around with the visual selection functionality I found a couple bugs.
1. When using visual line mode the functionality was just broken. Mainly because when visual line mode is used, the end_col and start_col will be out of bounds of the line. This makes sure to only trim the lines if the start_col and end_col are in the bounds of the lines
2. With the new ability to get the visual mode to pass into `update_prefills` I noticed that the current method for "leave visual mode" actually puts you into selection mode in the already open instance of grug-far which is very disorienting. This changes the method of leaving visual mode before getting the selection so that when updating the prefills you end up in the mode you expect in the grug-far window. While fixing this, I also …
> Visual selection utility fixes

- README.md
This PR addresses issue [#257](https://github.com/MagicDuck/grug-far.nvim/issues/257) by adding an integration recipe for using `grug-far.nvim` with `mini.files`.
Implemented a recipe that allows users to easily search within the current directory using grug-far while navigating files with mini.files. Fixed a couple of minor issues in the original recipe provided in the issue.
> docs: add recipe for searching and replacing in mini.files

- lua/grug-far.lua
- lua/grug-far/actions/historyOpen.lua
- lua/grug-far/engine/ripgrep/search.lua
- lua/grug-far/farBuffer.lua
- lua/grug-far/replacementInterpreter.lua
addresses https://github.com/MagicDuck/grug-far.nvim/issues/275
> adding more defensive logic around aborting search

- lua/grug-far/render/treesitter.lua
The get_parser and TSHighlight:new both parse the buffer which takes a lot of time since there are many error nodes, so set regions early to prevent this.
Fixes #286
> perf(treesitter): lazily get parser and set regions early

- lua/grug-far/render/treesitter.lua
@xzbdmw I have had to revert the previous fix partially due to seeing some weird stuff like text being partially highlighted. 
I did leave `parser:set_included_regions(regions)` call that you added in there, and did some measurements and it seems like the performance did not suffer.
> fixing some strange highlighting issues

- lua/grug-far/farBuffer.lua
fixes https://github.com/MagicDuck/grug-far.nvim/issues/328
> fixing undoing of backspace opt override when InsertLeave is not triggered (C-c, etc)

- lua/grug-far/actions/qflist.lua
I've found a small issue with the quickfix list integration.
Setting the replace flag when sending grug-far results into the quickfix list truncates existing results. That's a problem because the quickfix list keeps a history of all the lists generated during the session, and you can navigate the history with `:cprev` and `:cnext`. Which means that populating the list from grug overtakes whatever list is currently displaying.
For example, imagine you have the lists in `:chistory`
| | order | title |
|--------|--------|--------|
| | 1 | LSP references |
| | 2 | Some other plugin list |
| * | 3 | LSP references |
Then you navigate back to see the second list with `:cprev`.
| | order | title |
|--------|--------|--------|
| | 1 | LSP references |
| * | 2 | Some other plugin list |
| | 3 | …
> fix(quickfix list): avoid clobbering existing lists

- lua/grug-far/actions/historyOpen.lua
- lua/grug-far/farBuffer.lua
Since the mappings created by the plugin are local to the grug buffers, it shouldn't be necessary to put 'Grug Far: ' as a prefix.
> make keymaps' description shorter

- lua/grug-far.lua
- lua/grug-far/actions/historyOpen.lua
- lua/grug-far/actions/qflist.lua
- lua/grug-far/actions/search.lua
- lua/grug-far/actions/swapEngine.lua
- lua/grug-far/actions/swapReplacementInterpreter.lua
- lua/grug-far/engine.lua
- lua/grug-far/engine/astgrep.lua
- lua/grug-far/engine/astgrep/search.lua
- lua/grug-far/engine/ripgrep.lua
- lua/grug-far/engine/ripgrep/search.lua
- lua/grug-far/farBuffer.lua
- lua/grug-far/history.lua
- lua/grug-far/inputs.lua
- lua/grug-far/opts.lua
- lua/grug-far/render.lua
- lua/grug-far/render/resultsList.lua
helps with https://github.com/MagicDuck/grug-far.nvim/issues/363
With this change, we can:
1. we can omit rendering the Replace input for astgrep-rules
2. we could define labels for each input. So we could rename Search to Rules for astgrep-rules engine specifically.
3. we can have prefills respect those inputs
4. we can have history respect those input labels
5. we can define highlight lang for each input
> Refactoring so that inputs are specified per-engine

- .github/workflows/release.yml
to help with installations like rocks.nvim or lazy.nvim or plugins/neovim distributions that want to depend on it.
To be able to upload to luarocks, the owner of the luarocks account will have to add an API key named `LUAROCKS_API_KEY` to this repo's GitHub Actions secrets.
cc @mrcjkb
> feat: upload rockspec on a tag to luarocks.org

- lua/grug-far/health.lua
- lua/grug-far/opts.lua
- lua/grug-far/test/helpers.lua
- tests/astgrep-rules/test_search.lua
- tests/astgrep/test_search.lua
Continuation of https://github.com/MagicDuck/grug-far.nvim/pull/394.
I ran into an issue with `:checkhealth` breaking because grug-far was executing `sg`, which happened to be a different program and messed up my neovim instance each time I ran it. I saw you started the work and I thought I could just finish it.
> fix(ast-grep): rename binary from sg to ast-grep

- lua/grug-far/fold.lua
When setting `folding = { enabled = false }`, I would expect `foldcolumn` to be disabled too.
> fix(folds): disable `foldcolumn` when folding is disabled

- doc/grug-far-opts.txt
- lua/grug-far/farBuffer.lua
- lua/grug-far/opts.lua
- lua/types.lua
Fixes #519 
It bothered me that pressing delete in the input box didn't delete empty lines, but it looks like this was deliberate behavior. I have gone ahead and made it an option :) The video shows `backspaceEol` as `true`.
https://github.com/user-attachments/assets/5d5714e9-e10c-4499-8cf5-ccbfb805d676
> Add backspaceEol option to allow deleting eols in search box
