- CONTRIBUTING.md
- README.md
- lua/grug-far.lua
- lua/grug-far/actions/gotoLocation.lua
- lua/grug-far/farBuffer.lua
- lua/grug-far/render.lua
- lua/grug-far/utils.lua
> Fix dup buffer name issue and add filetype

- CONTRIBUTING.md
- README.md
- doc/grug-far.txt
- lua/grug-far.lua
- lua/grug-far/farBuffer.lua
- lua/grug-far/opts.lua
- lua/grug-far/render.lua
- lua/grug-far/render/results.lua
- lua/grug-far/rg/getArgs.lua
> Enrich lua api and make starting in insert mode / cursor position an option 

- lua/grug-far/rg/getArgs.lua
> removing hyperlink-format flag due to issues with lower versions of rg

- lua/grug-far/actions/replace.lua
- lua/grug-far/actions/search.lua
- lua/grug-far/actions/sync.lua
- lua/grug-far/rg/fetchWithRg.lua
there was some screwup in result aggregation due to how it was set up with vim.schedule()
> Fix results inconsistencies with rg

- lua/grug-far/actions/replace.lua
- lua/grug-far/actions/sync.lua
fixes https://github.com/MagicDuck/grug-far.nvim/issues/68
> updating opened buffers on replace / sync

- lua/grug-far.lua
- lua/grug-far/opts.lua
fixes https://github.com/MagicDuck/grug-far.nvim/issues/76
> adding window creation command option

- lua/grug-far/render/resultsList.lua
fixes https://github.com/MagicDuck/grug-far.nvim/issues/91
> calling redraw func only when available (new in 0.10)

- lua/grug-far.lua
Hi, great work with the plugin! Ive noticed something, i think the title gives it away.
> fix(grug-far): ensure with `with_visual_selection()` the `--fixed-strings` flag is added only once

- README.md
- lua/grug-far.lua
fixes https://github.com/MagicDuck/grug-far.nvim/issues/98
> returning toggle state

- lua/grug-far.lua
- lua/grug-far/actions/search.lua
- lua/grug-far/actions/toggleShowRgCommand.lua
- lua/grug-far/farBuffer.lua
- lua/grug-far/highlights.lua
- lua/grug-far/opts.lua
- lua/grug-far/render/resultsList.lua
- lua/grug-far/rg/fetchWithRg.lua
fixes https://github.com/MagicDuck/grug-far.nvim/issues/110
> adding toggleShowRgCommand

- lua/grug-far/rg/getArgs.lua
fixes https://github.com/MagicDuck/grug-far.nvim/issues/130
> forcing --max-columns=0

- lua/grug-far.lua
- lua/grug-far/opts.lua
fixes https://github.com/MagicDuck/grug-far.nvim/issues/133
> adding wrap option (default: true)

- lua/grug-far/farBuffer.lua
> fix: incorrect polarity for buffer listing

- lua/grug-far/utils.lua
This is a followup to #139 after some discussion. It removes the reliance on private APIs and only uses official API functions provided by Neovim.
> refactor: remove reliance on FFI and private APIs

- README.md
- lua/grug-far.lua
fixes https://github.com/MagicDuck/grug-far.nvim/issues/152
> adding support for command-mods

- lua/grug-far/actions/replace.lua
- lua/grug-far/rg/fetchReplacedFileContent.lua
- lua/grug-far/rg/fetchWithRg.lua
- lua/grug-far/utils.lua
addresses https://github.com/MagicDuck/grug-far.nvim/issues/160
> Improve replace logic to remove potential replace with empty content

- lua/grug-far/farBuffer.lua
addressing https://github.com/MagicDuck/grug-far.nvim/issues/168
> making cursor setting a pcall as there are issues in some situations

- README.md
- lua/grug-far.lua
related to https://github.com/MagicDuck/grug-far.nvim/issues/174
> upping nvim version due to usage of vim.iter

- lua/grug-far/actions/close.lua
fixes https://github.com/MagicDuck/grug-far.nvim/issues/185
> fixing error when closing last window

- README.md
As requested here: https://github.com/MagicDuck/grug-far.nvim/issues/165#issuecomment-2259546748
adding my advanced use-case
> DOCs nvim-tree integration example

- lua/grug-far/engine/astgrep.lua
fixes https://github.com/MagicDuck/grug-far.nvim/issues/199
> fixing multiple `no matches` messages

- lua/grug-far/engine/ripgrep/blacklistedReplaceFlags.lua
fixes https://github.com/MagicDuck/grug-far.nvim/issues/211
> allow --follow on replace

- lua/grug-far.lua
fixes https://github.com/MagicDuck/grug-far.nvim/issues/212
> fixing with_visual_selection in visual mode

- lua/grug-far/engine/syncChangedFiles.lua
for https://github.com/MagicDuck/grug-far.nvim/issues/219
> improving error message

- lua/grug-far/render.lua
- lua/grug-far/render/input.lua
- lua/grug-far/render/results.lua
- lua/grug-far/render/resultsList.lua
makes `Vp` work to paste
addresses https://github.com/MagicDuck/grug-far.nvim/issues/238
> improving copy-paste in inputs

- lua/grug-far/farBuffer.lua
- lua/grug-far/inputs.lua
- lua/grug-far/render.lua
- lua/grug-far/render/input.lua
addresses https://github.com/MagicDuck/grug-far.nvim/issues/238
> improve p / P / o  in inputs area

- lua/grug-far/actions/search.lua
- lua/grug-far/engine/astgrep/search.lua
- lua/grug-far/engine/ripgrep/search.lua
- lua/grug-far/render/resultsList.lua
- lua/grug-far/render/treesitter.lua
fixes https://github.com/MagicDuck/grug-far.nvim/issues/252
> Fix decoration provider highlighting error when pressing <cr> during results fetch

- lua/grug-far/fold.lua
fixes https://github.com/MagicDuck/grug-far.nvim/issues/264
> fixing folding for people remapping z

- lua/grug-far/actions/openLocation.lua
fixes https://github.com/MagicDuck/grug-far.nvim/issues/268
> fixing buffer polution when previewing

- doc/grug-far.txt
- lua/grug-far.lua
fixes https://github.com/MagicDuck/grug-far.nvim/issues/273
> fixing flags toggling

- lua/grug-far/actions/search.lua
- lua/grug-far/engine/fetchCommandOutput.lua
- lua/grug-far/render/resultsList.lua
addresses https://github.com/MagicDuck/grug-far.nvim/issues/275
> fixing error propagation

- lua/grug-far/farBuffer.lua
addresses https://github.com/MagicDuck/grug-far.nvim/issues/284
> fixing on_bytes error on close

- README.md
- lua/grug-far/engine/astgrep/getArgs.lua
- lua/grug-far/engine/astgrep/replace.lua
- lua/grug-far/engine/astgrep/search.lua
fixes https://github.com/MagicDuck/grug-far.nvim/issues/272
> using --globs option in newer astgrep

- lua/grug-far/actions/gotoLocation.lua
- lua/grug-far/actions/historyOpen.lua
- lua/grug-far/actions/openLocation.lua
- lua/grug-far/actions/previewLocation.lua
- lua/grug-far/utils.lua
addresses https://github.com/MagicDuck/grug-far.nvim/issues/304#issuecomment-2472145935
> improving escaping of file paths on windows based on neo-tree.nvim logic

- lua/grug-far/engine/fetchCommandOutput.lua
- lua/grug-far/engine/ripgrep/search.lua
fixes https://github.com/MagicDuck/grug-far.nvim/issues/310
> Fix inconsistent regex - part 2 - fixing some issues with \0 match separator

- README.md
- lua/grug-far/actions/applyChange.lua
- lua/grug-far/actions/openLocation.lua
- lua/grug-far/actions/sync.lua
- lua/grug-far/farBuffer.lua
- lua/grug-far/opts.lua
- lua/grug-far/test/helpers.lua
addresses https://github.com/MagicDuck/grug-far.nvim/issues/313
> adding apply prev/next action

- lua/grug-far/highlights.lua
fixes https://github.com/MagicDuck/grug-far.nvim/issues/317
> using different hl group for shortcut in help to improve visibility

- .github/workflows/tests.yml
- tests/screenshots/tests-astgrep-test_replace.lua---is-prevented-from-replacing-with-blacklisted-flags
fixes https://github.com/MagicDuck/grug-far.nvim/issues/316
> upping astgrep version used in tests

- lua/grug-far/actions/openLocation.lua
addresses https://github.com/MagicDuck/grug-far.nvim/issues/302
> preventing pollution of jumplist on open

- lua/grug-far/farBuffer.lua
fixes https://github.com/MagicDuck/grug-far.nvim/issues/328
> making sure latest backspace opt is used

- .github/workflows/.luarc.json
- .github/workflows/lint.yml
- lua/grug-far/actions/search.lua
- lua/grug-far/render/treesitter.lua
fixes https://github.com/MagicDuck/grug-far.nvim/issues/360
> adding message about minimum number of search chars to enter

- lua/grug-far/actions/applyChange.lua
- lua/grug-far/actions/openLocation.lua
- tests/base/test_apply.lua
fixes https://github.com/MagicDuck/grug-far.nvim/issues/365
> fixing moving between multiline results

- lua/grug-far/farBuffer.lua
close https://github.com/MagicDuck/grug-far.nvim/issues/371
> fix: can not get correct winid in FileType callback

- lua/grug-far/engine/astgrep/getAstgrepVersion.lua
- lua/grug-far/opts.lua
fixes https://github.com/MagicDuck/grug-far.nvim/issues/393
> switching default ast-grep executable to ast-grep

- README.md
- doc/grug-far.txt
- lua/grug-far.lua
- lua/grug-far/opts.lua
addresses https://github.com/MagicDuck/grug-far.nvim/issues/374#issuecomment-2711881992
> adding support for no-setup function call (vim.g.grug_far = {...})

- lua/grug-far.lua
- lua/grug-far/engine/astgrep-rules.lua
- lua/grug-far/engine/astgrep.lua
- lua/grug-far/engine/ripgrep.lua
- plugin/grug-far.lua
addresses https://github.com/MagicDuck/grug-far.nvim/issues/374
> moving autocommands to plugin/ dir

- doc/grug-far.txt
- lua/grug-far.lua
- lua/grug-far/farBuffer.lua
- lua/grug-far/inputs.lua
- lua/grug-far/opts.lua
- tests/base/test_inputs.lua
- tests/base/test_ui.lua
addresses https://github.com/MagicDuck/grug-far.nvim/issues/423
> Add inputs api

- lua/grug-far/opts.lua
for https://github.com/MagicDuck/grug-far.nvim/issues/424
> fixing multibyte lineNumberEllipsis

- lua/grug-far.lua
- lua/grug-far/opts.lua
- lua/grug-far/render/resultsList.lua
- tests/base/test_ui.lua
- tests/screenshots/tests-base-test_ui.lua---can-conceal-long-lines
for https://github.com/MagicDuck/grug-far.nvim/issues/437
> adding support for concealing part of file path when wrap=false

- lua/grug-far.lua
- lua/grug-far/fold.lua
for https://github.com/MagicDuck/grug-far.nvim/issues/441
> made folding code more defensive

- lua/grug-far.lua
- lua/grug-far/fold.lua
fixes https://github.com/MagicDuck/grug-far.nvim/issues/450
> fixing setting window opts on nvim 0.11

- lua/grug-far/render/resultsList.lua
fixes https://github.com/MagicDuck/grug-far.nvim/issues/452
> fixing up highlighting of consecutive lines

- lua/grug-far/render/resultsList.lua
for https://github.com/MagicDuck/grug-far.nvim/issues/459
> undojoin when adding lines to buffer

- README.md
- plugin/grug-far.lua
fixes https://github.com/MagicDuck/grug-far.nvim/issues/467
> indicating version that still works with nvim 0.10.0

- lua/grug-far/inputs.lua
for https://github.com/MagicDuck/grug-far.nvim/issues/482
> handling remapping of p/P/o for custom key layouts

- doc/grug-far-opts.txt
- lua/grug-far/farBuffer.lua
- lua/grug-far/inputs.lua
- lua/grug-far/opts.lua
for https://github.com/MagicDuck/grug-far.nvim/issues/482#issuecomment-2864704634
> adding flag for smartInputHandling

- lua/grug-far/engine/syncChangedFiles.lua
- lua/grug-far/utils.lua
for https://github.com/MagicDuck/grug-far.nvim/issues/485
> add support for detecing file line ending

- lua/grug-far/engine/ripgrep/parseResults.lua
- lua/grug-far/utils.lua
for https://github.com/MagicDuck/grug-far.nvim/issues/485
> ripgrep parser: detect trailing newline before stripping it

- doc/grug-far-api.txt
- doc/grug-far-instance-api.txt
- lua/grug-far.lua
- lua/grug-far/farBuffer.lua
- lua/grug-far/instances.lua
- lua/grug-far/test/helpers.lua
- tests/base/test_instance_api.lua
- tests/base/test_open.lua
https://github.com/MagicDuck/grug-far.nvim/issues/491
> returning instance from grugFar.open() and adding/wrapping inst:when_ready()

- doc/grug-far-instance-api.txt
- lua/grug-far/farBuffer.lua
- lua/grug-far/instances.lua
- tests/base/test_open.lua
- tests/screenshots/tests-base-test_open.lua---can-open-next-location-004
- tests/screenshots/tests-base-test_open.lua---can-open-prev-location-002
for https://github.com/MagicDuck/grug-far.nvim/issues/486
> Improve arrows - move to through input when arrowing up/down

- README.md
- doc/grug-far-opts.txt
- lua/grug-far.lua
- lua/grug-far/engine/astgrep/getArgs.lua
- lua/grug-far/engine/ripgrep/getArgs.lua
- lua/grug-far/fileIconsProvider.lua
- lua/grug-far/opts.lua
- lua/grug-far/pathProviders.lua
- lua/grug-far/utils.lua
- tests/base/test_instance_api.lua
- tests/base/test_search.lua
- tests/screenshots/tests-base-test_search.lua---can-search-for-some-string-in--buflist-
- tests/screenshots/tests-base-test_search.lua---can-search-for-some-string-in--buflist--001
- tests/screenshots/tests-base-test_search.lua---can-search-for-some-string-in--buflist-cwd-
- tests/screenshots/tests-base-test_search.lua---can-search-for-some-string-in--buflist-cwd--001
- tests/screenshots/tests-base-test_search.lua---can-search-for-some-string-in--loclist-
- tests/screenshots/tests-base-test_search.lua---can-search-for-some-string-in--loclist--001
- tests/screenshots/tests-base-test_search.lua---can-search-for-some-string-in--qflist-
- tests/screenshots/tests-base-test_search.lua---can-search-for-some-string-in--qflist--001
for https://github.com/MagicDuck/grug-far.nvim/issues/342
> adding path providers

- doc/grug-far-opts.txt
- lua/grug-far/opts.lua
- lua/grug-far/render.lua
- lua/grug-far/render/resultsHeader.lua
- lua/grug-far/utils.lua
for https://github.com/MagicDuck/grug-far.nvim/issues/503
> split padding opt

- Makefile
- doc/grug-far-highlights.txt
- lua/grug-far.lua
- lua/grug-far/engine.lua
- lua/grug-far/engine/astgrep.lua
- lua/grug-far/engine/astgrep/replace.lua
- lua/grug-far/engine/astgrep/search.lua
- lua/grug-far/engine/ripgrep.lua
- lua/grug-far/engine/ripgrep/replace.lua
- lua/grug-far/engine/ripgrep/search.lua
- lua/grug-far/engine/ripgrep/sync.lua
- lua/grug-far/highlights.lua
- lua/grug-far/render/resultsList.lua
- lua/grug-far/utils.lua
- lua/types.lua
for https://github.com/MagicDuck/grug-far.nvim/issues/517
> adding hl for visual selection of GrugFarWithin range

- doc/grug-far-opts.txt
- lua/grug-far.lua
- lua/grug-far/inputs.lua
https://github.com/MagicDuck/grug-far.nvim/issues/524
> fixing error when switching engine
